version: "3.8"
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: docker.env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "3001:3001"
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
    networks:
      - default
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - default
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  default:

volumes:
  local_pgdata:
  pgadmin-data:
